eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2222/eureka/
server:
  port: 9200
spring:
  application:
    name: server-zuul
zuul:
  routes:
    api-a:
      path: /api-member/**
      service-id: service-member
    api-b:
      path: /api-order/**
      service-id: service-order
