server:
  port: 8081
  servlet:
    context-path: /manager
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: service-manager
  datasource:
    url: jdbc:mysql://localhost:3306/manager?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password:
  jpa:
    show-sql: true #显示sql